# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring-system
    labels:
        app.kubernetes.io/name: grafana
stringData:
    gf_security_admin_user: ENC[AES256_GCM,data:7bZVTZQ=,iv:DmPKvFprKYPhIAobYZUlTNf3DkJOXLQRoaXJzGMe6ts=,tag:q6Di8Qa5RLcay7grOjH1bA==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:W9rY6BA8jH4=,iv:t5/Xb2J8ccPD74GRp5rFSA8OOl234uqFGDqJE5Ci9ro=,tag:66mrIuhgA+Zgk7RU2tsoNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f7ateukxpkm0srpep8vpsfv99wnjykfzt93znja2ljlhqjg33vaszenceq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNENnVUQ3Y01FS09mZk0x
            SkI5cjQxVVVwb1Rham04RkhYeDlEVE5pdFR3ClpkZFNPeUxVdGVzRzBTMkJmNXp6
            NU1FVjdHZ0IrdFpWYlVoeHFXUEprdHMKLS0tIE16MEpRQnp5ZXdsQkdkWGVteStx
            MzZVaGFHSUMwYnpjR2huTEJxdU9JSlkKqQFK1njH0OyfSB/zFsfAZN0LOzC8Tuns
            ic1MONghGLr0PfWDgBRr6Vo/wZOfiJINjNeezCws2tzImsqnO5R4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-09T19:30:38Z"
    mac: ENC[AES256_GCM,data:hnykWguwWT8NyxmOAy0R0ehTQ0UfxRjpCJHorYDDt7jUnKN15Q1aeZSgDQ+uwBOgA2iEO5C5BGGt1vpNtgCVRtAGjDEFwBQo0BaLLD9zxv5v6NkPAnwENjFInp+aR49SL/Udm8gOR8ItaOofWFk6QDhWDcc1ewj3ZpGOLlVSbc4=,iv:nB3+1++VE424ITJOJUEOuRfCEj+Mvb0T16s1Ajz0l2k=,tag:eVP9t2GigLN8RpS3hbJOVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
