# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8ViGSVmRc0yoO+ptlPB/Ilp4LwsV5QRHH03HCreOLz8jsW259Q==,iv:f50wDfwQg35WoZEBX75BsVbMGNLqOm9VTG+V0R/vjIg=,tag:rQZvn9xxRtbA/fSrjPsqeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f7ateukxpkm0srpep8vpsfv99wnjykfzt93znja2ljlhqjg33vaszenceq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR0xjbEl4M2FiYjRDNWh4
            Wi9mUU9TSTM1R1Npb0pOK00va2pOSE5XWmg0Cklnc1E4emVEbW9GdWFLanpNbE1j
            N0Q5am9BN01tUFpVWE1Id2hDekJnOHMKLS0tIDRhYzNPV3JUZlp3cUg3aSt1WW5l
            RHBNSlB1QUtrRVU1bitsb1JBakhyYTAKHAIf6oovPrYomBR+S6wfJrxvGkQ0dURQ
            62JWTMY80s++U5cHLipey9EK3w2ttxeY81jocsnyz8g+cJN64zVisA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-02T17:15:55Z"
    mac: ENC[AES256_GCM,data:CAAr0bzlRSBmEGHs7jsPGk1uO+Wm7yHixNmNpRVWSGZTHw+MdH0eRBpTjOj7qcgg+RJI/kukVImd93Xo/AyD1mvc027xUE+Dtl2cOgdf06acuTj5+Vi/Ug7RuEFhXeYS5jAvQhZ7k/rVftr5juQoF1rlI8cpoQxA3A6N48uGzMM=,iv:KjSPoExpIISibHI1cI2CTy3nT0EGtQWjYGLcXasd2hg=,tag:3HzywITlBvZzQNQTGPdJNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
